const express = require('express')
const app = express()
const axios = require('axios');
const cors = require('cors');
const bodyParser = require('body-parser');
const fs = require('fs');
var mysql = require('mysql');
const { waitForDebugger } = require('inspector');
const { sendToKafka } = require('../controllers/kafkaProduce');
const pool = mysql.createPool({
  host: "localhost",
  max_connections: "10000",
  user: "root",
  password: "root",
  database: "sales"
});

app.use(cors());
app.use(express.json());
app.use(bodyParser.urlencoded({ extended: true }));

app.post('/insert_sale', (req, res) => {
  const name = req.body.name;
  const flavor = req.body.flavor;
  const weight = req.body.weight;
  const date = req.body.date;
  var sqlInsert = "INSERT INTO salesData VALUE ('" + flavor + "', '" + date + "', '" + weight + "', '" + name + "')";
  var jsonSale = "{'flavor': '" + flavor + "', 'date': '" + date + "', 'weight': '" + weight + "', 'name': '" + name + "'}";
  sendToKafka(jsonSale);
  // pool.query(sqlInsert, (err, result) => {
  //   console.log(err);
  // });
});

app.post('/insert_branch', (req, res) => {
  const name = req.body.name;
  const city = req.body.city;
  const owner_details = req.body.owner_details;
  const vanila_stock = req.body.vanila_stock;
  const chocolate_stock = req.body.chocolate_stock;
  const lemon_stock = req.body.lemon_stock;
  const strawberry_stock = req.body.strawberry_stock;
  const halva_stock = req.body.halva_stock;
  var sqlInsert = "INSERT INTO Branches VALUE ('" + name + "', '" + city + "', '" + owner_details + "', '" + vanila_stock + "', '" +
    chocolate_stock + "', '" + lemon_stock + "', '" + halva_stock + "', '" + strawberry_stock + "')";
  var jsonBranch = "{'name': '" + name + "', 'city': '" + city + "', 'owner_details': '" + owner_details + "', 'vanila_stock': '" + vanila_stock + "'" + "', 'chocolate_stock': '" + chocolate_stock + "', 'lemon_stock': '" + lemon_stock + "', 'strawberry_stock': '" + strawberry_stock + "', 'halva_stock': '" + halva_stock + "'}";
  sendToKafka(jsonBranch);
  // pool.query(sqlInsert, (err, result) => {
  //   console.log(err);
  // });
});


app.post('/sales_simulation', (req, res) => {
  var randDate = randomDate(new Date(2022, 01, 01 ), new Date(2022, 12, 30));
  sales_lottery(randDate);
});

app.post('/sales_simulation_by_date', (req, res) => {
  sales_lottery(req.body.date);
});


app.listen(5000, () => { console.log("Server on port http://localhost:5000") })


async function add_sale_to_db(name, date, flavor, weight) {
  await axios.post('http://localhost:5000/insert_sale',
    { name: name, date: date, flavor: flavor, weight: weight });
}

async function add_branch_to_db(name, city, owner_details, vanila_stock, chocolate_stock, lemon_stock, halva_stock, strawberry_stock) {
  await axios.post('http://localhost:5000/insert_branch',
    {
      name: name, owner_details: owner_details, city: city, vanila_stock: vanila_stock,
      chocolate_stock: chocolate_stock, lemon_stock: lemon_stock, halva_stock: halva_stock, strawberry_stock: strawberry_stock
    });
}

function getrandomIntFromInterval(min, max) { // min and max included 
  return Math.floor(Math.random() * (max - min + 1) + min);
}

branch_names = ["SHAHAR",
"NIR HEN",
"HAZEVA",
"NO'AM",
"BET NIR",
"SEDE MOSHE",
"BE'ER ORA",
"MIQWE YISRA'EL",
"AMAZYA",
"LAKHISH",
"ROSH PINNA",
"SEDOT MIKHA",
"MAZKERET BATYA",
"YESUD HAMA'ALA",
"OFAQIM",
"OZEM",
"BAT SHELOMO",
"GADOT",
"SEDE DAWID",
"ETAN",
"GEFEN",
"ELYAKHIN",
"METULA",
"ZOHAR",
"YAVNE'EL",
"KEFAR TAVOR",
"MENAHEMYA",
"ILANIYYA",
"LUZIT",
"ATLIT",
"NOGAH",
"KINNERET(QEVUZA)",
"MIZPA",
"NEHUSHA",
"DEGANYA ALEF",
"KINNERET(MOSHAVA)",
"YAD RAMBAM",
"MIGDAL",
"MERHAVYA(QIBBUZ)",
"OR HANER",
"NIR OZ",
"ASHDOD",
"ESHBOL",
"GAN SHEMU'EL",
"EN HOD",
"KEFAR GIL'ADI",
"AYYELET HASHAHAR",
"QIRYAT ANAVIM",
"DEGANYA BET",
"NAHALAL",
"EN HAROD(ME'UHAD)",
"KEFAR YEHEZQEL",
"GEVA",
"KEREM BEN SHEMEN",
"EN HAROD (IHUD)",
"HEFZI-BAH",
"GINNEGAR",
"BALFURYA",
"BET ALFA",
"YAGUR",
"MERHAVYA(MOSHAV)",
"KEFAR MALAL",
"MIZPE RAMON",
"ME'IR SHEFEYA",
"MIZRA",
"KEFAR GID'ON",
"KEFAR SILVER",
"KEFAR HASIDIM ALEF",
"ADDIRIM",
"HOFIT",
"RAMAT YISHAY",
"RAMAT RAHEL",
"GAT RIMMON",
"MISHMAR HAEMEQ",
"KEFAR BARUKH",
"GEVAT",
"YIF'AT",
"RAMAT DAWID",
"EN SHEMER",
"KEFAR YEHOSHUA",
"BARAQ",
"SEDE YA'AQOV",
"BET ZERA",
"GAN SHELOMO",
"GADISH",
"DEVORA",
"GIV'AT BRENNER",
"BE'ER TOVIYYA",
"AYANOT",
"EN WERED",
"NA'AN",
"BET HANAN",
"HULDA",
"HERUT",
"MELE'A",
"NIR YAFE",
"GAN YAVNE",
"EN HAHORESH",
"KEFAR YONA",
"KEFAR YA'BEZ",
"PARDESIYYA",
"GIV'AT HAYYIM(ME'UHAD)",
"NETA'IM",
"AVIHAYIL",
"AFIQIM",
"KEFAR BILU",
"RAMAT YOHANAN",
"EVEN YEHUDA",
"YARQONA",
"RAMAT HAKOVESH",
"NE'URIM",
"KEFAR HESS",
"ASHDOT YA'AQOV(ME'UHAD)",
"KEFAR PINES",
"KEFAR VITKIN",
"HADAR AM",
"KEFAR HAHORESH",
"KEFAR HAYYIM",
"MISHMAR HASHARON",
"QADIMA-ZORAN",
"GIBBETON",
"MA'BAROT",
"ZOFIT",
"ASHDOT YA'AQOV(IHUD)",
"BET YANNAY",
"BET OVED",
"ELYASHIV",
"HOGLA",
"RAMOT HASHAVIM",
"GIV'AT HEN",
"MOZA ILLIT",
"BET ZEVI",
"MISHMAROT",
"KEFAR HARO'E",
"GANNE AM",
"HIBBAT ZIYYON",
"KEFAR BIALIK",
"EN IRON",
"SHOSHANNAT HAAMAQIM",
"GAN HASHOMERON",
"GANNE TIQWA",
"MA'AS",
"KEFAR YEDIDYA",
"BIZZARON",
"HAVAZZELET HASHARON",
"GAN HAYYIM",
"YOQNE'AM ILLIT",
"YOQNE'AM(MOSHAVA)",
"BET HASHITTA",
"NETIVOT",
"RISHPON",
"BET SHE'ARIM",
"KEFAR SIRKIN",
"HAZOREA",
"BITAN AHARON",
"HULATA",
"KEFAR HAMAKKABBI",
"KEFAR HITTIM",
"NIR DAWID (TEL AMAL)",
"NOFEKH",
"SEDE NAHUM",
"GINNOSAR",
"MASSADA",
"BET YOSEF",
"KEFAR SHEMARYAHU",
"TIRAT ZEVI",
"MOLEDET",
"EN HASHOFET",
"MA'OZ HAYYIM",
"EN GEV",
"KEFAR MENAHEM",
"ZUR MOSHE",
"USHA",
"HANITA",
"PEQI'IN HADASHA",
"SHAVE ZIYYON",
"SEDE WARBURG",
"ALLONIM",
"MA'ALE HAHAMISHA",
"BET YEHOSHUA",
"EN HAMIFRAZ",
"MA'YAN ZEVI",
"SEDE YO'AV",
"ELON",
"KEFAR RUPPIN",
"NEWE ETAN",
"KEFAR MASARYK",
"MESILLOT",
"DALIYYA",
"BET UZZI'EL",
"DAFNA",
"DAN",
"SEDE ELIYYAHU",
"GESHER",
"SHADMOT DEVORA",
"HAZORE'IM",
"MAHANAYIM",
"NEHORA",
"KEFAR GLIKSON",
"GAN SOREQ",
"NEWE YAM",
"AFEQ",
"NEGBA",
"KEFAR NETTER",
"BET OREN",
"AMMI'OZ",
"AMIR",
"KEFAR WARBURG",
"BET HILLEL",
"SHE'AR YASHUV",
"MAZZUVA",
"BET YIZHAQ-SH. HEFER",
"SEDOT YAM",
"EZUZ",
"SEDE NEHEMYA",
"ALUMMOT",
"NIR ZEVI",
"QEVUZAT YAVNE",
"RAMAT HASHOFET",
"DOROT",
"IBBIM",
"RAMAT ZEVI",
"GAT(QIBBUZ)",
"GEVAR'AM",
"HAMADYA",
"MA'ANIT",
"KEFAR SZOLD",
"GELIL YAM",
"MENARA",
"NIR AM",
"NIZZAN",
"GEVULOT",
"BET ZEID",
"REVIVIM",
"HORESHIM",
"HAGOSHERIM",
"KEFAR BLUM",
"YAD MORDEKHAY",
"NIZZANIM",
"GIV'AT NILI",
"RUHAMA",
"HAFEZ HAYYIM",
"KEFAR URIYYA",
"BET QESHET",
"SHAMIR",
"EN HAEMEQ",
"BIRIYYA",
"GAL'ED (EVEN YIZHAQ)",
"GEZER",
"KADOORIE",
"RAMOT NAFTALI",
"BET HALEWI",
"HUQOQ",
"MAGGAL",
"EVRON",
"HAMA'PIL",
"MISGAV AM",
"GE'ULIM",
"LAHAVOT HABASHAN",
"MIKHMORET",
"EN HANAZIV",
"AMMI'AD",
"BENE DEROR",
"KEFAR MONASH",
"KEFAR KISCH",
"BAZRA",
"REGBA",
"GAL'ON",
"SHOVAL",
"MISHMAR HANEGEV",
"NEVATIM",
"HAZERIM",
"BE'ERI",
"EVEN SHEMU'EL",
"NIR YIZHAQ",
"URIM",
"NEWE ILAN",
"HAZOR-ASHDOD",
"DAVERAT",
"NE'OT MORDEKHAY",
"YEHI'AM",
"QIRYAT SHELOMO",
"ZE'ELIM",
"QELAHIM",
"SHOQEDA",
"MA'YAN BARUKH",
"YAQUM",
"BENE ZIYYON",
"SA'AD",
"MASH'ABBE SADE",
"HEREV LE'ET",
"HAOGEN",
"GEVIM",
"MISHMERET",
"EN KARMEL",
"KEFAR GALLIM",
"BEROR HAYIL",
"ALLONE ABBA",
"BET LEHEM HAGELILIT",
"DALTON",
"SHAMERAT",
"NAHSHOLIM",
"HAHOTERIM",
"NEZER SERENI",
"EN DOR",
"RESHAFIM",
"SHELUHOT",
"YESODOT",
"GID'ONA",
"KEFAR HANASI",
"REGAVIM",
"RAMOT MENASHE",
"UDIM",
"NORDIYYA",
"BENE ATAROT",
"NEHALIM",
"BE'EROT YIZHAQ",
"YIZRE'EL",
"YIFTAH",
"SA'AR",
"SHORESH",
"GAZIT",
"RAMAT RAZI'EL",
"TAL SHAHAR",
"GA'TON",
"HAR'EL",
"ZOVA",
"BET DAGAN",
"QIRYAT EQRON",
"ABU GHOSH",
"ABU SINAN",
"DAHI",
"IKSAL",
"BEIT JANN",
"MUGHAR",
"BU'EINE-NUJEIDAT",
"BI'NE",
"JULIS",
"JISH(GUSH HALAV)",
"DABURIYYA",
"DEIR AL-ASAD",
"DEIR HANNA",
"DEIR RAFAT",
"DALIYAT AL-KARMEL",
"HURFEISH",
"TAYIBE(BAEMEQ)",
"TUR'AN",
"YAFI",
"YIRKA",
"KABUL",
"KAOKAB ABU AL-HIJA",
"KAFAR YASIF",
"KAFAR KAMA",
"KAFAR KANNA",
"KAFAR MANDA",
"ILUT",
"KAFAR MISR",
"EIN RAFA",
"MAJD AL-KURUM",
"MAZRA'A",
"MI'ELYA",
"MESHHED",
"EIN NAQQUBA",
"NAHEF",
"NEIN",
"NA'URA",
"SAJUR",
"SULAM",
"SHEZOR",
"UZEIR",
"I'BILLIN",
"EILABUN",
"ARRABE",
"EIN MAHEL",
"ISIFYA",
"FASSUTA",
"PEQI'IN (BUQEI'A)",
"FUREIDIS",
"RUMMANE",
"REIHANIYYE",
"JISR AZ-ZARQA",
"REINE",
"RAME",
"EIN AL-ASAD",
"TAMRA (YIZRE'EL)",
"GANNOT HADAR",
"NIR BANIM",
"SHEDEMA",
"BUSTAN HAGALIL",
"BET EL'AZARI",
"MISHMAR DAWID",
"REVADIM",
"AZOR",
"GIV'AT SHEMESH",
"ZOR'A",
"ME'ONA",
"BET GAMLI'EL",
"BET HAEMEQ",
"MAVQI'IM",
"GESHER HAZIW",
"YAS'UR",
"KABRI",
"YAD BINYAMIN",
"SASA",
"KEFAR ROSH HANIQRA",
"KEREM MAHARAL",
"KEFAR HANAGID",
"ZIQIM",
"LAVI",
"MEGIDDO",
"SAVYON",
"BENE RE'EM",
"BEZET",
"NEWE UR",
"ASERET",
"BENE DAROM",
"ARUGOT",
"ZAFRIYYA",
"LOHAME HAGETA'OT",
"MALKIYYA",
"PALMAHIM",
"BET QAMA",
"PAROD",
"NIRIM",
"ELQOSH",
"BET ARIF",
"KEFAR SHAMMAY",
"MAZOR",
"MERON",
"KEFAR HOSHEN",
"SITRIYYA",
"ZERUFA",
"ZIPPORI",
"SHOMERA",
"QIDRON",
"RINNATYA",
"BARQAY",
"HADID",
"BET GUVRIN",
"MASSU'OT YIZHAQ",
"EN ZURIM",
"YIR'ON",
"JALJULYE",
"JATT",
"KAFAR BARA",
"KAFAR QASEM",
"MUQEIBLE",
"SANDALA",
"AR'ARA",
"QALANSAWE",
"MEZER",
"MEISER",
"IBTIN",
"KAFAR QARA",
"SHEIKH DANNUN",
"HOSEN",
"TIRAT YEHUDA",
"KEREM BEN ZIMRA",
"OMER",
"BAR'AM",
"MEFALLESIM",
"MISHMAR AYYALON",
"BET NEQOFA",
"KEFAR TRUMAN",
"LIMAN",
"HABONIM",
"EN HASHELOSHA",
"HASOLELIM",
"MA'AGAN",
"AVI'EL",
"OMEZ",
"GIV'AT SHEMU'EL",
"ELYAQIM",
"GEVA KARMEL",
"HAYOGEV",
"BENAYA",
"NEWE YAMIN",
"EN AYYALA",
"ALMA",
"MEGADIM",
"KEFAR AHIM",
"NETIV HALAMED-HE",
"MA'AGAN MIKHA'EL",
"MAGEN",
"KEFAR HABAD",
"BE'EROTAYIM",
"BURGETA",
"NIR YISRA'EL",
"HAZAV",
"ARBEL",
"HAON",
"GIV'AT OZ",
"NAHSHONIM",
"GE'A",
"KEFAR DANIYYEL",
"AMQA",
"BET ZAYIT",
"AZARYA",
"BEN AMMI",
"RE'IM",
"EREZ",
"LAHAVOT HAVIVA",
"EYAL",
"HAGOR",
"YARHIV",
"NIR GALLIM",
"SEDE ILAN",
"MAGSHIMIM",
"BET HAGADDI",
"HODIYYA",
"MISHMAR HASHIV'A",
"ELIFELET",
"MESHAR",
"MISHMAR HAYARDEN",
"GAN YOSHIYYA",
"RAMOT ME'IR",
"GILAT",
"OLESH",
"DOR",
"SEDE UZZIYYAHU",
"ESHTA'OL",
"SHO'EVA",
"MESILLAT ZIYYON",
"KEFAR SHEMU'EL",
"GIMZO",
"BEREKHYA",
"BET SHIQMA",
"MASLUL",
"PATTISH",
"PEDUYIM",
"BET ME'IR",
"YANUV",
"GOREN",
"BET EZRA",
"MAZLIAH",
"YAD HANNA",
"YAZIZ",
"BEN ZAKKAY",
"SHUVA",
"BITHA",
"KEFAR MORDEKHAY",
"MISGAV DOV",
"QOMEMIYYUT",
"PORAT",
"KARMIYYA",
"NIR EZYON",
"MEVO BETAR",
"EMUNIM",
"AMMIQAM",
"ZURI'EL",
"YAD NATAN",
"MAHSEYA",
"NAHSHON",
"AMMINADAV",
"ORA",
"EVEN SAPPIR",
"BET NEHEMYA",
"AHIHUD",
"KEFAR ZETIM",
"GIV'AT YE'ARIM",
"ZETAN",
"RANNEN",
"MASH'EN",
"NETIV HASHAYYARA",
"GIV'ATI",
"AGUR",
"YA'ARA",
"ZELAFON",
"AHI'EZER",
"YAGEL",
"ZEKHARYA",
"BET HANANYA",
"HEMED",
"GIV'AT KOAH",
"YOSHIVYA",
"AHISAMAKH",
"YISH'I",
"EN YAHAV",
"HANNI'EL",
"NIR ELIYYAHU",
"NAHAM",
"OFER",
"YAKHINI",
"SHELOMI",
"EN YA'AQOV",
"ZAVDI'EL",
"ZANOAH",
"AZRIQAM",
"ZERAHYA",
"AVIGEDOR",
"HELEZ",
"AHUZZAM",
"MATTA",
"BAR GIYYORA",
"KOKHAV MIKHA'EL",
"NES HARIM",
"UZA",
"NEWE MIVTAH",
"YASHRESH",
"MIVTAHIM",
"YEROHAM",
"NURIT",
"GANNOT",
"AZRI'EL",
"PEDAYA",
"PETAHYA",
"KISSUFIM",
"ELISHAMA",
"GA'ASH",
"MARGALIYYOT",
"NAHAL OZ",
"KEFAR AZZA",
"BET RABBAN",
"DEVIRA",
"AHITUV",
"NIZZANE OZ",
"GONEN",
"GE'ALYA",
"REHOV",
"KEFAR AVIV",
"NEWE YARAQ",
"KESALON",
"SEDE ELI'EZER",
"GANNE YOHANAN",
"GINNATON",
"BEQOA",
"SHIBBOLIM",
"YOTVATA",
"ALLONE YIZHAQ",
"GIV'AT HASHELOSHA",
"ENAT",
"GE'ULE TEMAN",
"SHALWA",
"MIGDAL HAEMEQ",
"BET HERUT",
"EN SARID",
"ORANIM",
"SEDE BOQER",
"ETANIM",
"KEFAR HARIF",
"KEFAR HASIDIM BET",
"KEFAR HANO'AR HADATI",
"AVDON",
"MIDRESHET RUPPIN",
"SHIBLI-UMM AL-GHANAM",
"YESHA",
"ATSMON SEGEV",
"GIV'AT YESHA'YAHU",
"REKHASIM",
"NEWE AVOT",
"SAWA'ID(HAMRIYYE)",
"BASMAT TAB'UN",
"TUBA-ZANGARIYYE",
"ZARZIR",
"KA'ABIYYE-TABBASH-HAJAJRE",
"RAS ALI",
"HAMAM",
"MANSHIYYET ZABDA",
"RUMAT HEIB",
"BIR EL-MAKSUR",
"MEVASSERET ZIYYON",
"OR AQIVA",
"HARUZIM",
"SEDEROT",
"QIRYAT MAL'AKHI",
"GIZO",
"YE'AF",
"OHAD",
"HAZON",
"BET HASHMONAY",
"QETURA",
"EN KAREM-B.S.HAQLA'I",
"NEWE ZOHAR",
"SEDE NIZZAN",
"KUSEIFE",
"LAQYE",
"NOF HAGALIL",
"MA'ALOT-TARSHIHA",
"AMIRIM",
"ZIMRAT",
"BENE AYISH",
"DOVEV",
"ADAMIT",
"RAM-ON",
"AVI'EZER",
"NEWE MIKHA'EL",
"GAN HADAROM",
"BET BERL",
"GIV'AT SHAPPIRA",
"ZAFRIRIM",
"MABBU'IM",
"EVEN MENAHEM",
"MA'GALIM",
"BEN SHEMEN(K.NO'AR)",
"KEREM SHALOM",
"KEREM YAVNE(YESHIVA)",
"KEFAR MAYMON",
"MERKAZ SHAPPIRA",
"ZUQI YAM",
"GANNE HADAR",
"PORIYYA-KEFAR AVODA",
"PORIYYA-NEWE OVED",
"OMEN",
"HEVER",
"YODEFAT",
"ZUR HADASSA",
"AVIVIM",
"ADDERET",
"NE'OT HAKIKKAR",
"ALMAGOR",
"ELOT",
"MA'ALE GILBOA",
"ME AMMI",
"GEROFIT",
"KEFAR ROZENWALD(ZARIT)",
"WARDON",
"YAD HASHEMONA",
"ZOHAR",
"QIRYAT YE'ARIM",
"YA'AD",
"KARMI'EL",
"MIDRESHET BEN GURION",
"MEVO MODI'IM",
"NES AMMIM",
"YEDIDA",
"ALUMMA",
"ALUMIM",
"NETU'A",
"ZUR NATAN",
"EZER",
"ZOFAR",
"PARAN",
"ASHALIM",
"KISHOR",
"MALKISHUA",
"MAGEN SHA'UL",
"SAMAR",
"AHAWA",
"YAHEL",
"SHEKHANYA",
"RAHAT",
"BET RIMMON",
"MORAN",
"SHILAT",
"KEFAR RUT",
"QESARYYA",
"LOTEM",
"LAPPIDOT",
"MANOF",
"IDDAN",
"SAPPIR",
"TELALIM",
"MORESHET",
"QORANIT",
"ZVIYYA",
"TAL-EL",
"ALLON HAGALIL",
"KELIL",
"MATTAT",
"PELEKH",
"HOSHA'AYA",
"ESHHAR",
"MIZPE NETOFA",
"BAR YOHAY",
"AR'ARA-BANEGEV",
"NIZZANA (QEHILAT HINUH)",
"MAHANE YATTIR",
"NE'OT SMADAR",
"KERAMIM",
"ADI",
"MODI'IN-MAKKABBIM-RE'UT",
"KAMMON",
"MIKHMANNIM",
"HARARIT",
"GILON",
"MANOT",
"GITTA",
"LAVON",
"HILLA",
"HARASHIM",
"KAHAL",
"QADDARIM",
"AMUQQA",
"ZIV'ON",
"TEFAHOT",
"GORNOT HAGALIL",
"ABBIRIM",
"ZURIT",
"MIZPE AVIV",
"SEDE AVRAHAM",
"KOKHAV YA'IR",
"RAVID",
"YUVALLIM",
"YATED",
"RAQQEFET",
"KALLANIT",
"LIVNIM",
"PERI GAN",
"YEVUL",
"SHORASHIM",
"NIRIT",
"SUFA",
"HOLIT",
"EN HABESOR",
"DEQEL",
"NETIV HAASARA",
"QAZIR",
"SALLAMA",
"ARAMSHA",
"HARISH",
"ELIFAZ",
"HARDUF",
"EN TAMAR",
"KORAZIM",
"AMNUN",
"NATAF",
"LOTAN",
"ASHERAT",
"HANNATON",
"MASSAD",
"NEWE SHALOM",
"RETAMIM",
"HAR AMASA",
"ZUQIM",
"KEFAR WERADIM",
"KARME YOSEF",
"SHOMERIYYA",
"SHAHARUT",
"METAR",
"LEHAVIM",
"HALUZ",
"GAN NER",
"AVTALYON",
"ESHBAL",
"BE'ER MILKA",
"NEWE HARIF",
"NIZZANE SINAY",
"MERAV",
"NOFIT",
"KARKOM",
"SEGEV-SHALOM",
"SHANI",
"GIV'AT ELA",
"ZEMER",
"KEMEHIN",
"JUDEIDE-MAKER",
"GIV'AT AVNI",
"OR HAGANUZ",
"YANUH-JAT",
"KISRA-SUMEI",
"KEFAR HANANYA",
"HURA",
"SHOHAM",
"EL'AD",
"LAPPID",
"AVSHALOM",
"PORIYYA ILLIT",
"NEWE ZIV",
"MATTAN",
"AL-ARYAN",
"DEMEIDE",
"MEVO'OT YAM",
"BAT HEFER",
"EIN HOD",
"KHAWALED",
"HODAYOT",
"BAT HADAR",
"ARSUF",
"KEFAR ZOHARIM",
"BASMA",
"MA'ALE IRON",
"AHUZZAT BARAQ",
"KAMANE",
"HUSSNIYYA",
"NOF AYYALON",
"RAS AL-EIN",
"ARAB AL NAIM",
"IRUS",
"SHIMSHIT",
"KADDITA",
"AL-AZY",
"MERHAV AM",
"ABU QUREINAT",
"MAKCHUL",
"GEVA'OT BAR",
"ZUR YIZHAQ",
"QASR A-SIR",
"BIR HADAGE",
"DERIG'AT",
"UMM BATIN",
"AL SAYYID",
"SA'WA",
"BAT HEN",
"BNE NETSARIM",
"SHLOMIT",
"ELIAV",
"NAVE",
"KOCHLEA",
"BNE DEQALIM",
"NETA",
"MITSPE ILAN",
"GANNE TAL",
"NEZER HAZZANI",
"KARME KATIF",
"ABU TULUL",
"BE'ER GANNIM",
"SHAVE DAROM",
"SHEZAF",
"NIZZAN B",
"KANNOT",
"SEDE YIZHAQ",
"YUVAL",
"KEFAR BIN NUN",
"YINNON",
"OROT",
"BEN SHEMEN (MOSHAV)",
"GIV'OLIM",
"SEDE HEMED",
"REWAYA",
"GIV'AT HAYYIM (IHUD)",
"ESHEL HANASI",
"LAHAV",
"UMM AL-QUTUF",
"YARDENA",
"MIDRAKH OZ",
"MENUHA",
"BET HILQIYYA",
"HAZOR HAGELILIT",
"ADANIM",
"BAREQET",
"QIRYAT YE'ARIM(INSTITUTE)",
"EN GEDI",
"BAHAN",
"MELILOT",
"NAHALA",
"SEGULLA",
"NIR MOSHE",
"NIR AQIVA",
"SEDE ZEVI",
"REWAHA",
"AVITAL",
"PERAZON",
"METAV",
"MA'OR",
"SEDE TERUMOT",
"PA'AME TASHAZ",
"BEROSH",
"DISHON",
"ZERU'A",
"TIRAT KARMEL",
"DIMONA",
"QIRYAT TIV'ON",
"OR YEHUDA",
"NESHER",
"BE'ER YA'AQOV",
"GEDERA",
"ARAD",
"ELAT",
"BET SHEMESH",
"QIRYAT ONO",
"QIRYAT GAT",
"ROSH HAAYIN",
"RAMAT HASHARON",
"YAVNE",
"UMM AL-FAHM",
"TIRE",
"TAYIBE",
"QIRYAT SHEMONA",
"JERUSALEM",
"KEFAR EZYON",
"NETIV HAGEDUD",
"ALMOG",
"QEDUMIM",
"ELQANA",
"MIGDAL OZ",
"KOKHAV HASHAHAR",
"RIMMONIM",
"YAFIT",
"SAL'IT",
"REHAN",
"MEVO DOTAN",
"ARI'EL",
"SHAVE SHOMERON",
"KEFAR TAPPUAH",
"NEVE TSUF",
"BET EL",
"BET HORON",
"MIZPE YERIHO",
"SHADMOT MEHOLA",
"ELON MORE",
"ARGAMAN",
"MEHOLA",
"QALYA",
"ROSH ZURIM",
"HAR GILLO",
"ALLON SHEVUT",
"MASSU'A",
"GILGAL",
"YITAV",
"MA'ALE EFRAYIM",
"HAMRA",
"MIZPE SHALEM",
"QIRYAT ARBA",
"BEQA'OT",
"GITTIT",
"MEKHORA",
"PEZA'EL",
"MA'ALE ADUMMIM",
"OFRA",
"EL'AZAR",
"RO'I",
"NA'ARAN",
"KEFAR ADUMMIM",
"WERED YERIHO",
"QARNE SHOMERON",
"SHILO",
"HINNANIT",
"GIV'ON HAHADASHA",
"BET HAARAVA",
"HEMDAT",
"YAQIR",
"MATTITYAHU",
"EFRAT",
"MA'ALE MIKHMAS",
"BET ARYE-OFARIM",
"MA'ALE AMOS",
"BARQAN",
"NILI",
"KARMEL",
"MA'ON",
"ATERET",
"PESAGOT",
"IMMANU'EL",
"MEVO HORON",
"BERAKHA",
"ENAV",
"NA'AMA",
"ALMON",
"HERMESH",
"ESHKOLOT",
"PENE HEVER",
"NEGOHOT",
"NEWE DANIYYEL",
"NOQEDIM",
"ALE ZAHAV",
"GIV'AT ZE'EV",
"TENE",
"BRUKHIN",
"MEZADOT YEHUDA",
"QIRYAT NETAFIM",
"DOLEV",
"OTNI'EL",
"YIZHAR",
"ALFE MENASHE",
"MIGDALIM",
"MA'ALE LEVONA",
"ASFAR",
"SUSEYA",
"ADORA",
"ORANIT",
"ITAMAR",
"GEVA BINYAMIN",
"HAGGAY",
"ELI",
"KARME ZUR",
"NAHALI'EL",
"PEDU'EL",
"HAR ADAR",
"HASHMONA'IM",
"SANSANA",
"KOKHAV YA'AQOV",
"BETAR ILLIT",
"QEDAR",
"ROTEM",
"SHIM'A",
"MASKIYYOT",
"AVENAT",
"NA'ALE",
"TALMON",
"NOFIM",
"ZUFIM",
"AVNE HEFEZ",
"BAT AYIN",
"REVAVA",
"KEFAR HAORANIM",
"MODI'IN ILLIT",
"REHELIM",
"GANNE MODI'IN",
"AMMIHAY",
"MEVO'OT YERIHO",
"HAIFA",
"BUQ'ATA",
"ELI-AD",
"EL-ROM",
"KEFAR HARUV",
"HASPIN",
"QESHET",
"YONATAN",
"MA'ALE GAMLA",
"ODEM",
"AVNE ETAN",
"ANI'AM",
"ORTAL",
"NATUR",
"BENE YEHUDA",
"ALLONE HABASHAN",
"MEZAR",
"GIV'AT YO'AV",
"GESHUR",
"QELA",
"QIDMAT ZEVI",
"HAD-NES",
"KANAF",
"QAZRIN",
"MEROM GOLAN",
"MAJDAL SHAMS",
"MAS'ADE",
"MEVO HAMMA",
"AFIQ",
"NEWE ATIV",
"NOV",
"GHAJAR",
"EIN QINIYYE",
"EN ZIWAN",
"NE'OT GOLAN",
"RAMAT MAGSHIMIM",
"RAMOT",
"BAQA AL-GHARBIYYE",
"BENE BERAQ",
"BAT YAM",
"GIV'ATAYIM",
"HERZLIYYA",
"HADERA",
"HOLON",
"TIBERIAS",
"QIRYAT ATTA",
"KEFAR SAVA",
"LOD",
"ASHQELON",
"NES ZIYYONA",
"NAZARETH",
"NETANYA",
"SAKHNIN",
"AKKO",
"AFULA",
"PARDES HANNA-KARKUR",
"PETAH TIQWA",
"ZEFAT",
"QIRYAT MOTZKIN",
"RISHON LEZIYYON",
"REHOVOT",
"RAMLA",
"RAMAT GAN",
"RA'ANNANA",
"TAMRA",
"BE'ER SHEVA",
"NAHARIYYA",
"BET SHE'AN",
"ZIKHRON YA'AQOV",
"YEHUD-MONOSON",
"QIRYAT BIALIK",
"QIRYAT YAM",
"HOD HASHARON",
"BINYAMINA-GIV'AT ADASHAHAR",
"MEQ"];

sales = [];
flavors = ["Chocolate", "Vanilla", "Strawberry", "Lemon", "Halva"];
weights = [0.25, 1, 1.5, 2];

function sales_lottery(date) {
  var date= new Date(date);
  for (branch = 0; branch < 40; branch++) { //for every branch
    for (flavor = 0; flavor < flavors.length; flavor++) { //for every flavor
      num_sells = getrandomIntFromInterval(0, 2); //lottery num of sells
      for (sale_num = 0; sale_num < num_sells; sale_num++) { //for the certain num of sells
        weight = weights[getrandomIntFromInterval(0, weights.length - 1)]; //lottery weight
        branch_name = branch_names[branch];
        add_sale_to_db(branch_name, date, flavors[flavor], weight);
      }
    }
  }
}

function sleep(milliseconds) {
  const date = Date.now();
  let currentDate = null;
  do {
    currentDate = Date.now();
  } while (currentDate - date < milliseconds);
}

//create_branches();
function create_branches() {
  for (branch_num = 0; branch_num < 100; branch_num++) {
    var flavors_stock = new Map();
    for (let flavor = 0; flavor < flavors.length; flavor++) { //for every flavor decide stock
      flavors_stock.set(flavors[flavor], getrandomIntFromInterval(0, 100));
    }
    add_branch_to_db(branch_names[branch_num], branch_names[branch_num], "owner of branch number: " + branch_num, flavors_stock.get("Vanilla"), flavors_stock.get("Chocolate"), flavors_stock.get("Lemon"), flavors_stock.get("Halva"), flavors_stock.get("Strawberry"));
  }
}

function randomDate(start, end) {
  return new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()));
}
  //Reference:
  // server and client splitting:
  // https://www.youtube.com/watch?v=w3vs4a03y3I
  // NavBar tutorial:
  // https://www.youtube.com/watch?v=SLfhMt5OUPI
  // generating random date:
  // https://stackoverflow.com/questions/9035627/elegant-method-to-generate-array-of-random-dates-within-two-dates